# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'EdgeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EdgeApp
pod 'Firebase/Core'
pod 'Firebase/Messaging'

  #target 'EdgeApp-tvOSTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  target 'EdgeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EdgeApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EdgeApp-tvOS

  target 'EdgeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
